### PR TITLE
Add missing @throws annotation

### PR DESCRIPTION
**Pull request by VincentLanglet**
Cf https://github.com/jolicode/elastically/pull/160#issuecomment-1593688166

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@damienalexandre @lyrixx 

I added all the @throws annotation and configured PHPStan for it.

The 4 tests failing are about unrelated deprecations since SF 6.3 is released.

**Review by lyrixx — APPROVED** [review]
Thanks

**Review by damienalexandre — APPROVED** [review]
Looks good to me, thanks a lot

**Comment by VincentLanglet** [comment]
You're welcome. If you have time for a release, this would be perfect :)

**Comment by damienalexandre** [comment]
We need to fix the tests and update the changelog before releasing 😬 If someone has time today? (I don't 🙈)

**Comment by VincentLanglet** [comment]
Since the deprecation is coming from generated code, this issue need to be solve https://github.com/janephp/janephp/issues/727

Simpler solution may be to change the `<server name="SYMFONY_DEPRECATIONS_HELPER" value="max[direct]=0"/>` config

**Comment by lyrixx** [comment]
Good to me 👍🏼 Would you mind to subit a PR?

**Comment by VincentLanglet** [comment]
Sure https://github.com/jolicode/elastically/pull/172

**Comment by damienalexandre** [comment]
v1.8.4 is released!

**Pull request merged**
