### PR TITLE
Update to allow Symfony 7 and test on PHP 8.3

### PR DESCRIPTION
**Pull request by NicolasDievart**
Hi

I've updated the composer.json to allow Symfony ^7.0 and change the CI layout to test it against SF 7 but also 8.3 which release few days ago.

Do you want to keep supporting SF 5.4 (which ended its bug fixes period and entered security fix only https://symfony.com/releases/5.4) ? I can update this PR accordingly
I can also update to only allow 6.4 version instead of all 6.* if needed.

### CODE REVIEW

**Comment by damienalexandre** [comment]
Hi! Thanks for the contribution :heart: 

Yes I would like to keep Symfony 5.4 as it's the LTS version right now.

Looks like we have a dependency issue with Jane:

```
   Problem 1
    - Root composer.json requires jane-php/json-schema ^7.4 -> satisfiable by jane-php/json-schema[v7.4.0, ..., v7.5.5].
    - jane-php/json-schema[v7.4.0, ..., v7.5.5] require symfony/console ^4.4 || ^5.0 || ^6.0 -> found symfony/console[v4.4.0, ..., v4.4.49, v5.0.0, ..., v5.4.32, v6.0.0, ..., v6.4.1] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - jane-php/json-schema-runtime[v7.4.0, ..., v7.5.5] require symfony/serializer ^4.4 || ^5.0 || ^6.0 -> found symfony/serializer[v4.4.0, ..., v4.4.47, v5.0.0, ..., v5.4.33, v6.0.0, ..., v6.4.1] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires jane-php/json-schema-runtime ^7.4 -> satisfiable by jane-php/json-schema-runtime[v7.4.0, ..., v7.5.5].
```

**Comment by NicolasDievart** [comment]
Good catch :+1: 
Will need this PR to be reviewed, merged and released then https://github.com/janephp/janephp/pull/774 

I let the PR as is with SF 5.4 :)

**Comment by insekticid** [comment]
any news here? 
https://github.com/janephp/janephp/pull/774 has been merged!

**Comment by damienalexandre** [comment]
It has been close in favor or https://github.com/janephp/janephp/pull/768 ; which is still open :crossed_fingers:

**Comment by damienalexandre** [comment]
I'm currently looking at this PR as JanePHP is now compatible with SF7.

**Comment by damienalexandre** [comment]
Thanks a lot for your contribution! A release will be done today :+1:

**Pull request merged**
