### PR TITLE
Solve SF 7 deprecation

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @damienalexandre @lyrixx,

I'm getting the following deprecation with SF 7
```
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "JoliCode\Elastically\Bridge\Symfony\DependencyInjection\ElasticallyExtension".
```

This PR fix it.

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
Thanks

**Comment by damienalexandre** [comment]
Thanks a lot!

**Comment by VincentLanglet** [comment]
You're welcome, could you consider a patch release @damienalexandre ?
Thanks

**Comment by damienalexandre** [comment]
Yes here it is: https://github.com/jolicode/elastically/releases/tag/v1.9.2

**Pull request merged**
