### PR TITLE
Drop support for PHP < 7.4

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by damienalexandre** [comment]
Can you explain why, the pros and the cons? I see no feature that require this change.

**Comment by lyrixx** [comment]
PHP 7.2 is not supported

**Comment by lyrixx** [comment]
I forgot to explain the cons: there are none

**Comment by lyrixx** [comment]
Actually, I already made this PR and my fork was really outdated: https://github.com/jolicode/elastically/commit/72bd083a187b536be514a3644672ecbd687edf01

**Pull request closed without merging**
