### PR TITLE
Invalid transport issue

### LINKED ISSUE #139: Symfony config + HttpClient gives "Invalid transport"
Hi,

I'm currently testing the new Symfony bundle, and I'm facing this issue when trying to index data:

```
In AbstractTransport.php line 129:
                                         
  [Elastica\Exception\InvalidException]  
  Invalid transport 
```

When I dump() the $transport before the if() statement, I get a string instead of a service:
`@JoliCode\Elastically\Transport\HttpClientTransport`

Here is my (truncated) Elastically config:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    JoliCode\Elastically\Messenger\DocumentExchangerInterface:
        alias: App\Elasticsearch\DocumentExchanger

    JoliCode\Elastically\Transport\HttpClientTransport: ~

elastically:
    connections:
        default:
            client:
                host: '%env(ELASTICSEARCH_HOST)%'
                port: '%env(ELASTICSEARCH_PORT)%'
                transport: '@JoliCode\Elastically\Transport\HttpClientTransport'
            mapping_directory: '%kernel.project_dir%/config/elasticsearch'
            bulk_size: 100
            prefix: formations_%kernel.environment%
            index_class_mapping:
                sector: App\Elasticsearch\Model\Sector

framework:
    messenger:
        transports:
            sync: 'sync://'
        routing:
            'JoliCode\Elastically\Messenger\IndexationRequest': sync
```

Did I miss something?

### PR DESCRIPTION
**Pull request by Korbeil**
Fixes #139 

Tested with https://github.com/Korbeil/test-elastically-140. Copy current branch in vendors then run `app:debug` command, you'll have to see the transport in the connection as following:
image

### CODE REVIEW

**Comment by jmsche** [comment]
Thank you @Korbeil, it seems to work well :) 

Could you also please update the README file? That's where I took the `@JoliCode\Elastically\Transport\HttpClientTransport` with the `@` sign.

**Comment by Korbeil** [comment]
I did in the PR I think, I'll check once at work

**Comment by jmsche** [comment]
The DI config example was indeed updated, but not the readme :)

**Comment by Korbeil** [comment]
And done, thanks for the feedback :pray:

**Review by jmsche — APPROVED** [review]

**Pull request merged**
